version: '3'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lmmu_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lmmu_network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: lmmu_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - lmmu_network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: lmmu_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lmmu_network
    ports:
      - "3307:3306"

# Networks
networks:
  lmmu_network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
